module.exports = ClientEvents = {
    connect: 'connect', 
    connect_timeout: 'connect_timeout',
    connect_error: 'connect_error',
    error: 'error',
    disconnect: 'disconnect',
    reconnect: 'reconnect',
    reconnect_attempt: 'reconnect_attempt',
    reconnecting: 'reconnecting',
    reconnect_error: 'reconnect_error',
    reconnect_failed: 'reconnect_failed',
    ping: 'ping',
    pong: 'pong',
    packet_sending: 'packet_sending',
    packet_timeout: 'packet_timeout',
    packet_failed: 'packet_failed',
    login_success: 'login_success',
    login_failed: 'login_failed',
    logout_success: 'logout_success',
    logout_failed: 'logout_failed',
    message_group_subscribe_success: 'message_group_subscribe_success',
    message_group_subscribe_failed: 'message_group_subscribe_failed',
    message_private_subscribe_success: 'message_private_subscribe_success',
    message_private_subscribe_failed: 'message_private_subscribe_failed'
}